apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-auth-v1
  namespace: business-center-test
  labels:
    app: business-auth
    app.kubernetes.io/name: business-center
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    kubesphere.io/description: "统一认证中心 - 接口"
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: business-auth
      app.kubernetes.io/name: business-center
      app.kubernetes.io/version: v1
      version: v1
  template:
    metadata:
      labels:
        app: business-auth
        app.kubernetes.io/name: business-center
        app.kubernetes.io/version: v1
        version: v1
      annotations:
        kubesphere.io/containerSecrets: '{"business-auth":"harbor"}'
    spec:
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          imagePullPolicy: Always
          name: business-auth
          ports:
            - containerPort: 8080
              name: tcp-8080
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: '8080'
          resources:
            limits:
              cpu: 1500m
              memory: 1024Mi
            requests:
              cpu: 20m
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: harbor
