yzcloud:
  cors-headers: yz-auth-pool-id,Authorization,Token,content-type,access-token,accesstoken
nacos:
  config:
    server-addr: https://center-nacos.app-chengdu1.yunzhicloud.com
    namespace: ca75c1d1-9a68-410b-9721-40da085036af
    bootstrap:
      enable: true