apiVersion: v1
kind: Service
metadata:
  labels:
    app: business-auth
    app.kubernetes.io/name: business-center
    app.kubernetes.io/version: v1
  name: business-auth
  namespace: business-center-test
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: business-auth
    app.kubernetes.io/name: business-center
    app.kubernetes.io/version: v1
  sessionAffinity: None
  type: ClusterIP
